### PR TITLE
docs: fix the Chinese README failed to find error

### PR DESCRIPTION
**Pull request by richzw**
Fix the Chinese README failed to find error

### CODE REVIEW

**Comment by DjangoPeng** [comment]
We need to continuously maintain the Chinese version in line with the progress of the course. :)

**Comment by richzw** [comment]
> Nope. The Chinese version of README for whole project that is still waiting for a PR.
> 
> We'd better create a PR for it. @richzw

Sorry for misunderstanding it before. Maybe I could create another PR for the Chinese README

**Comment by richzw** [comment]
> Nope. The Chinese version of README for whole project that is still waiting for a PR.
> 
> We'd better create a PR for it. @richzw

Another PR https://github.com/DjangoPeng/openai-quickstart/pull/20 for the README CN. Could you please review it? @DjangoPeng

**Comment by DjangoPeng** [comment]
我们在 #20 讨论，这个先关闭了

**Pull request closed without merging**
