### PR TITLE
feat: add 7/30 schedule to README

### PR DESCRIPTION
**Pull request by richzw**
Add 7/30 schedule to README/README-CN

### CODE REVIEW

**Comment by DjangoPeng** [comment]
Nice move!

**Comment by DjangoPeng** [comment]
@richzw The link of code `pdfplumber` is a wrong path. Please fix it in another PR.

**Comment by richzw** [comment]
> @richzw The link of code `pdfplumber` is a wrong path. Please fix it in another PR.

Got it, I will fix it in another PR.

**Comment by richzw** [comment]
> @richzw The link of code `pdfplumber` is a wrong path. Please fix it in another PR.

@DjangoPeng  The fix is in this PR https://github.com/DjangoPeng/openai-quickstart/pull/36

**Pull request merged**
